/**
 * Enhanced Contracts Components
 * 
 * New UI/UX components for the contracts page, featuring:
 * - Hero Dashboard with stats and trends
 * - Enhanced Contract Cards with health indicators
 * - Contract Preview Panel (email-app style)
 * - Smart Filters with AI-powered suggestions
 * - Floating Bulk Actions Bar
 * - Mobile-optimized views
 * 
 * @author Generated by AI Assistant
 * @version 2.0.0
 */

// Hero Dashboard
export {
  ContractsHeroDashboard,
  type ContractStats,
  type ContractsHeroDashboardProps,
} from "./ContractsHeroDashboard";

// Enhanced Contract Cards
export {
  EnhancedContractCard,
  EnhancedContractRow,
  PartyAvatar,
  HealthIndicator,
  ExpiryBadge,
  CompletenessBar,
  QuickPreview,
  type EnhancedContract,
  type ContractParty,
  type ContractHealth,
  type EnhancedContractCardProps,
  type EnhancedContractRowProps,
} from "./EnhancedContractCard";

// Contract Preview Panel
export {
  ContractPreviewPanel,
  type ExtendedContract,
  type ContractActivity,
  type ContractClause,
  type ContractAttachment,
  type ContractPreviewPanelProps,
} from "./ContractPreviewPanel";

// Enhanced Bulk Actions Bar
export {
  EnhancedBulkActionsBar,
  type BulkAction,
  type BulkActionResult,
  type EnhancedBulkActionsBarProps,
} from "./EnhancedBulkActionsBar";

// Smart Filters
export {
  SmartFilters,
  type ContractFilters,
  type FilterPreset,
  type ContractStatus,
  type RiskLevel,
  type SmartFiltersProps,
} from "./SmartFilters";

// Mobile Views
export {
  MobileContractCard,
  MobileSearchBar,
  MobileFiltersSheet,
  MobilePullToRefresh,
  MobileFAB,
  MobileEmptyState,
  MobileStatsSummary,
  type MobileContractCardProps,
  type MobileFiltersSheetProps,
  type MobileSearchBarProps,
  type PullToRefreshProps,
  type MobileFABProps,
  type MobileEmptyStateProps,
  type MobileStatsSummaryProps,
} from "./MobileContractViews";
