/**
 * SAML Service Provider Metadata
 * GET /api/auth/saml/metadata
 *
 * Returns SP metadata XML generated by samlify.
 */

import { NextRequest, NextResponse } from 'next/server';
import { getSpMetadata } from '@/lib/auth/saml-service';

export const dynamic = 'force-dynamic';

export async function GET(_request: NextRequest) {
  try {
    const metadata = getSpMetadata();
    return new NextResponse(metadata, {
      headers: {
        'Content-Type': 'application/samlmetadata+xml',
        'Cache-Control': 'no-store',
      },
    });
  } catch {
    return new NextResponse('Metadata generation failed', { status: 500 });
  }
}
