packages:
  - apps/*
  - '!apps/sharepoint-app'
  - packages/*
  - packages/clients/*
  - infra

onlyBuiltDependencies:
  - es5-ext
  - fsevents
  - keytar
  - node-sass
  - puppeteer
  - tesseract.js
