/**
 * PowerPoint Export Service for Negotiation Prep
 * Generates professional presentation slides
 * 
 * NOTE: This is a simplified version. For production, install pptxgenjs:
 * npm install pptxgenjs
 * 
 * Then uncomment the pptxgenjs implementation below.
 */

export interface PowerPointOptions {
  includeTitle: boolean
  includeExecutiveSummary: boolean
  includeMarketAnalysis: boolean
  includeRecommendations: boolean
  includeTalkingPoints: boolean
  includeScenarios: boolean
  template: 'professional' | 'modern' | 'minimal'
  companyName?: string
  preparedBy?: string
}

export interface SlideData {
  role: string
  level: string
  location: string
  supplier: string
  currentRate: number
  targetRate: number
  marketMedian: number
  percentile: number
  potentialSavings: number
  strategy: string
  confidence: number
  talkingPoints: string[]
  scenarios: Array<{
    name: string
    rate: number
    savings: number
  }>
}

export class PowerPointExportService {
  /**
   * Generate PowerPoint presentation
   */
  static async generatePresentation(
    data: SlideData,
    options: PowerPointOptions
  ): Promise<Blob> {
    // Simplified version - returns a placeholder
    // In production, this would use pptxgenjs to create actual slides
    
    const content = this.generateTextContent(data, options)
    const blob = new Blob([content], { type: 'text/plain' })
    
    return blob
  }

  /**
   * Download PowerPoint file
   */
  static downloadPresentation(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = filename
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  /**
   * Generate text content (placeholder for actual PowerPoint)
   */
  private static generateTextContent(data: SlideData, options: PowerPointOptions): string {
    let content = ''

    if (options.includeTitle) {
      content += `NEGOTIATION PREPARATION PRESENTATION\n`
      content += `${data.role} - ${data.level}\n`
      content += `${data.location}\n\n`
      if (options.companyName) {
        content += `Prepared for: ${options.companyName}\n`
      }
      if (options.preparedBy) {
        content += `Prepared by: ${options.preparedBy}\n`
      }
      content += `Date: ${new Date().toLocaleDateString()}\n\n`
      content += `${'='.repeat(60)}\n\n`
    }

    if (options.includeExecutiveSummary) {
      content += `EXECUTIVE SUMMARY\n\n`
      content += `Current Rate: CHF ${data.currentRate.toLocaleString()}\n`
      content += `Target Rate: CHF ${data.targetRate.toLocaleString()}\n`
      content += `Potential Savings: CHF ${data.potentialSavings.toLocaleString()}\n`
      content += `Market Position: ${data.percentile}th percentile\n`
      content += `Recommended Strategy: ${data.strategy}\n`
      content += `Confidence: ${data.confidence}%\n\n`
      content += `${'='.repeat(60)}\n\n`
    }

    if (options.includeMarketAnalysis) {
      content += `MARKET ANALYSIS\n\n`
      content += `Market Median: CHF ${data.marketMedian.toLocaleString()}\n`
      content += `Your Position: ${data.percentile}th percentile\n`
      content += `Supplier: ${data.supplier}\n`
      content += `Location: ${data.location}\n\n`
      content += `${'='.repeat(60)}\n\n`
    }

    if (options.includeRecommendations) {
      content += `RECOMMENDATIONS\n\n`
      content += `Strategy: ${data.strategy}\n`
      content += `Confidence Level: ${data.confidence}%\n`
      content += `Target Rate: CHF ${data.targetRate.toLocaleString()}\n`
      content += `Expected Savings: CHF ${data.potentialSavings.toLocaleString()}\n\n`
      content += `${'='.repeat(60)}\n\n`
    }

    if (options.includeTalkingPoints && data.talkingPoints.length > 0) {
      content += `KEY TALKING POINTS\n\n`
      data.talkingPoints.forEach((point, index) => {
        content += `${index + 1}. ${point}\n`
      })
      content += `\n${'='.repeat(60)}\n\n`
    }

    if (options.includeScenarios && data.scenarios.length > 0) {
      content += `SCENARIO ANALYSIS\n\n`
      data.scenarios.forEach(scenario => {
        content += `${scenario.name}:\n`
        content += `  Rate: CHF ${scenario.rate.toLocaleString()}\n`
        content += `  Savings: CHF ${scenario.savings.toLocaleString()}\n\n`
      })
      content += `${'='.repeat(60)}\n\n`
    }

    content += `END OF PRESENTATION\n`
    content += `Generated by ChainIQ Negotiation Prep Tool\n`

    return content
  }

  /**
   * Get available templates
   */
  static getTemplates(): Array<{
    id: string
    name: string
    description: string
    preview?: string
  }> {
    return [
      {
        id: 'professional',
        name: 'Professional',
        description: 'Classic business presentation with charts and data'
      },
      {
        id: 'modern',
        name: 'Modern',
        description: 'Contemporary design with bold colors and graphics'
      },
      {
        id: 'minimal',
        name: 'Minimal',
        description: 'Clean and simple layout focusing on key information'
      }
    ]
  }
}

/* 
 * PRODUCTION IMPLEMENTATION WITH PPTXGENJS
 * 
 * Uncomment this after installing pptxgenjs:
 * 
 * import pptxgen from 'pptxgenjs'
 * 
 * export class PowerPointExportService {
 *   static async generatePresentation(data: SlideData, options: PowerPointOptions): Promise<Blob> {
 *     const pptx = new pptxgen()
 *     
 *     // Set presentation properties
 *     pptx.author = options.preparedBy || 'ChainIQ'
 *     pptx.company = options.companyName || 'ChainIQ'
 *     pptx.title = 'Negotiation Preparation'
 *     
 *     // Title Slide
 *     if (options.includeTitle) {
 *       const slide = pptx.addSlide()
 *       slide.addText('Negotiation Preparation', {
 *         x: 0.5, y: 1.5, w: 9, h: 1,
 *         fontSize: 44, bold: true, color: '363636'
 *       })
 *       slide.addText(`${data.role} - ${data.level}`, {
 *         x: 0.5, y: 2.5, w: 9, h: 0.5,
 *         fontSize: 24, color: '666666'
 *       })
 *     }
 *     
 *     // Executive Summary Slide
 *     if (options.includeExecutiveSummary) {
 *       const slide = pptx.addSlide()
 *       slide.addText('Executive Summary', {
 *         x: 0.5, y: 0.5, w: 9, h: 0.75,
 *         fontSize: 32, bold: true
 *       })
 *       
 *       const summaryData = [
 *         ['Metric', 'Value'],
 *         ['Current Rate', `CHF ${data.currentRate.toLocaleString()}`],
 *         ['Target Rate', `CHF ${data.targetRate.toLocaleString()}`],
 *         ['Potential Savings', `CHF ${data.potentialSavings.toLocaleString()}`],
 *         ['Market Position', `${data.percentile}th percentile`],
 *         ['Strategy', data.strategy],
 *         ['Confidence', `${data.confidence}%`]
 *       ]
 *       
 *       slide.addTable(summaryData, {
 *         x: 1, y: 1.5, w: 8, h: 3,
 *         fontSize: 14
 *       })
 *     }
 *     
 *     // Generate blob
 *     const blob = await pptx.write('blob')
 *     return blob as Blob
 *   }
 * }
 */
