/**
 * Artifact Document Export Service
 *
 * Generates professional PDF and DOCX documents from artifact data.
 * Uses jspdf (PDF) and docx (DOCX) libraries already in dependencies.
 *
 * Supported formats: PDF, DOCX, JSON, CSV (existing)
 *
 * @version 1.0.0
 */

import { jsPDF } from 'jspdf';
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
  WidthType,
  AlignmentType,
  BorderStyle,
  ShadingType,
  Footer,
  PageNumber,
  NumberFormat,
} from 'docx';

// =============================================================================
// TYPES
// =============================================================================

export interface ArtifactExportInput {
  artifact: {
    id: string;
    type: string;
    data: Record<string, any>;
    confidence?: number | null;
    qualityScore?: number | null;
    completenessScore?: number | null;
    createdAt?: string | Date;
    updatedAt?: string | Date;
    modelUsed?: string | null;
  };
  contract?: {
    fileName?: string | null;
    contractType?: string | null;
    parties?: string[];
  };
  tenantName?: string;
}

// =============================================================================
// PDF EXPORT
// =============================================================================

/**
 * Generate a professional PDF document from artifact data.
 * Returns a Uint8Array of the PDF content.
 */
export function generateArtifactPDF(input: ArtifactExportInput): Uint8Array {
  const { artifact, contract, tenantName } = input;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Colors
  const primary = [37, 99, 235];  // blue-600
  const dark = [30, 41, 59];      // slate-800
  const muted = [100, 116, 139];  // slate-500
  const bg = [248, 250, 252];     // slate-50

  // --- Header ---
  doc.setFillColor(primary[0], primary[1], primary[2]);
  doc.rect(0, 0, pageWidth, 35, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(formatArtifactTitle(artifact.type), margin, 15);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const subtitle = contract?.fileName
    ? `${contract.fileName} • ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`
    : new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  doc.text(subtitle, margin, 23);

  if (tenantName) {
    doc.setFontSize(9);
    doc.text(tenantName, pageWidth - margin, 15, { align: 'right' });
  }

  y = 45;

  // --- Metadata bar ---
  doc.setFillColor(bg[0], bg[1], bg[2]);
  doc.rect(margin, y, contentWidth, 12, 'F');
  doc.setTextColor(muted[0], muted[1], muted[2]);
  doc.setFontSize(8);

  const metaParts: string[] = [];
  if (artifact.confidence != null) metaParts.push(`Confidence: ${Math.round(Number(artifact.confidence) * 100)}%`);
  if (artifact.qualityScore != null) metaParts.push(`Quality: ${artifact.qualityScore}/100`);
  if (artifact.modelUsed) metaParts.push(`Model: ${artifact.modelUsed}`);
  if (contract?.contractType) metaParts.push(`Type: ${contract.contractType}`);
  doc.text(metaParts.join('  •  '), margin + 3, y + 8);

  y += 20;

  // --- Content ---
  doc.setTextColor(dark[0], dark[1], dark[2]);
  y = renderArtifactContent(doc, artifact.type, artifact.data, margin, y, contentWidth);

  // --- Footer ---
  const pageCount = doc.internal.pages.length - 1;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(muted[0], muted[1], muted[2]);
    doc.text(
      `Generated by ConTigo AI  •  Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' },
    );
  }

  return doc.output('arraybuffer') as unknown as Uint8Array;
}

function formatArtifactTitle(type: string): string {
  return type.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()) + ' Report';
}

function renderArtifactContent(
  doc: jsPDF,
  type: string,
  data: Record<string, any>,
  margin: number,
  startY: number,
  contentWidth: number,
): number {
  let y = startY;
  const pageHeight = doc.internal.pageSize.getHeight() - 20;

  function checkPage() {
    if (y > pageHeight - 30) {
      doc.addPage();
      y = 20;
    }
  }

  function heading(text: string, level: 1 | 2 = 1) {
    checkPage();
    doc.setFontSize(level === 1 ? 14 : 11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 41, 59);
    doc.text(text, margin, y);
    y += level === 1 ? 8 : 6;
  }

  function body(text: string) {
    checkPage();
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85);
    const lines = doc.splitTextToSize(String(text || '—'), contentWidth);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 3;
  }

  function keyValue(key: string, value: any) {
    if (value == null || value === '') return;
    checkPage();
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(100, 116, 139);
    doc.text(`${key}:`, margin, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85);
    const valStr = typeof value === 'object' ? JSON.stringify(value) : String(value);
    const lines = doc.splitTextToSize(valStr, contentWidth - 40);
    doc.text(lines, margin + 40, y);
    y += Math.max(lines.length * 4.5, 5) + 2;
  }

  // Render based on artifact type
  switch (type) {
    case 'OVERVIEW': {
      const val = (key: string) => data[key]?.value ?? data[key];
      heading('Contract Overview');
      keyValue('Contract Name', val('contractName') || val('title'));
      keyValue('Type', val('contractType'));
      keyValue('Status', data.status);
      keyValue('Effective Date', val('effectiveDate'));
      keyValue('Expiration Date', val('expirationDate'));
      keyValue('Total Value', formatMoney(data.totalValue));
      keyValue('Governing Law', val('governingLaw'));

      if (data.parties?.length) {
        heading('Parties', 2);
        for (const p of data.parties) {
          keyValue(p.role || 'Party', p.name);
        }
      }

      if (val('executiveSummary')) {
        heading('Executive Summary', 2);
        body(val('executiveSummary'));
      }
      break;
    }

    case 'CLAUSES': {
      heading('Key Clauses');
      const clauses = data.clauses || data.items || [];
      for (const clause of clauses) {
        checkPage();
        heading(clause.title || clause.name || 'Clause', 2);
        if (clause.category) keyValue('Category', clause.category);
        if (clause.riskLevel) keyValue('Risk Level', clause.riskLevel);
        body(clause.fullText || clause.text || clause.summary || '');
      }
      break;
    }

    case 'FINANCIAL': {
      heading('Financial Summary');
      keyValue('Total Value', formatMoney(data.totalValue));
      keyValue('Currency', data.currency);
      if (data.paymentTerms) {
        heading('Payment Terms', 2);
        if (typeof data.paymentTerms === 'string') {
          body(data.paymentTerms);
        } else {
          keyValue('Net Days', data.paymentTerms.netDays);
          keyValue('Method', data.paymentTerms.paymentMethod);
          keyValue('Schedule', data.paymentTerms.invoicingSchedule);
        }
      }
      if (data.fees?.length) {
        heading('Fees', 2);
        for (const fee of data.fees) {
          keyValue(fee.name, `${formatMoney(fee)} (${fee.frequency || 'one-time'})`);
        }
      }
      break;
    }

    case 'RISK': {
      heading('Risk Assessment');
      if (data.overallRiskScore) {
        keyValue('Overall Score', `${data.overallRiskScore.value}/10 (${data.overallRiskScore.category})`);
      }
      const risks = data.risks || data.items || [];
      for (const risk of risks) {
        checkPage();
        heading(risk.title || risk.name || 'Risk', 2);
        keyValue('Severity', risk.severity || risk.level);
        keyValue('Category', risk.category);
        body(risk.description || '');
        if (risk.mitigation || risk.recommendation) {
          keyValue('Mitigation', risk.mitigation || risk.recommendation);
        }
      }
      break;
    }

    case 'COMPLIANCE': {
      heading('Compliance Report');
      keyValue('Overall Score', data.overallScore ?? data.complianceScore);
      keyValue('Status', data.status);
      if (data.frameworks?.length) {
        heading('Frameworks', 2);
        for (const fw of data.frameworks) {
          keyValue(fw.name, fw.compliant ? '✓ Compliant' : '✗ Non-compliant');
        }
      }
      if (data.gaps?.length) {
        heading('Gaps', 2);
        for (const gap of data.gaps) {
          body(`• ${typeof gap === 'string' ? gap : gap.description || JSON.stringify(gap)}`);
        }
      }
      break;
    }

    case 'OBLIGATIONS': {
      heading('Obligations');
      const sections = [
        ['Buyer Obligations', data.buyerObligations],
        ['Seller Obligations', data.sellerObligations],
        ['Mutual Obligations', data.mutualObligations],
      ] as const;
      for (const [title, items] of sections) {
        if (items?.length) {
          heading(title, 2);
          for (const ob of items) {
            body(`• ${ob.description || ob.text || ob.obligation || ''}`);
            if (ob.deadline || ob.dueDate) keyValue('  Deadline', ob.deadline || ob.dueDate);
          }
        }
      }
      break;
    }

    default: {
      heading(formatArtifactTitle(type));
      for (const [key, value] of Object.entries(data)) {
        if (key === 'extractionMetadata') continue;
        if (Array.isArray(value)) {
          heading(key.replace(/([A-Z])/g, ' $1').trim(), 2);
          for (const item of value.slice(0, 20)) {
            if (typeof item === 'string') {
              body(`• ${item}`);
            } else if (typeof item === 'object') {
              const display = item.title || item.name || item.description || JSON.stringify(item);
              body(`• ${display}`);
            }
          }
        } else if (typeof value === 'object' && value !== null) {
          keyValue(key, value.value ?? JSON.stringify(value));
        } else {
          keyValue(key, value);
        }
      }
    }
  }

  return y;
}

function formatMoney(val: any): string {
  if (!val) return '';
  if (typeof val === 'number') return `$${val.toLocaleString()}`;
  if (val.value != null) return `${val.currency || '$'}${Number(val.value).toLocaleString()}`;
  return String(val);
}

// =============================================================================
// DOCX EXPORT
// =============================================================================

/**
 * Generate a professional Word (.docx) document from artifact data.
 * Returns a Uint8Array (the .docx binary).
 */
export async function generateArtifactDOCX(input: ArtifactExportInput): Promise<Uint8Array> {
  const { artifact, contract, tenantName } = input;
  const children: Paragraph[] = [];

  // Title
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: formatArtifactTitle(artifact.type),
          bold: true,
          size: 36,
          color: '2563EB',
          font: 'Calibri',
        }),
      ],
      heading: HeadingLevel.TITLE,
      spacing: { after: 200 },
    }),
  );

  // Subtitle
  const subtitleParts = [
    contract?.fileName,
    contract?.contractType ? `Type: ${contract.contractType}` : null,
    new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
  ].filter(Boolean);
  
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: subtitleParts.join('  •  '),
          size: 20,
          color: '64748B',
          font: 'Calibri',
        }),
      ],
      spacing: { after: 300 },
    }),
  );

  // Metadata
  const metaParts: string[] = [];
  if (artifact.confidence != null) metaParts.push(`Confidence: ${Math.round(Number(artifact.confidence) * 100)}%`);
  if (artifact.qualityScore != null) metaParts.push(`Quality: ${artifact.qualityScore}/100`);
  if (artifact.modelUsed) metaParts.push(`Model: ${artifact.modelUsed}`);
  
  if (metaParts.length > 0) {
    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: metaParts.join('  •  '), size: 18, color: '94A3B8', italics: true }),
        ],
        spacing: { after: 400 },
      }),
    );
  }

  // Horizontal rule
  children.push(new Paragraph({
    border: { bottom: { color: 'E2E8F0', style: BorderStyle.SINGLE, size: 1, space: 1 } },
    spacing: { after: 300 },
  }));

  // Content
  renderDocxContent(children, artifact.type, artifact.data);

  const doc = new Document({
    creator: tenantName || 'ConTigo AI',
    title: formatArtifactTitle(artifact.type),
    description: `AI-generated ${artifact.type.toLowerCase()} analysis`,
    sections: [
      {
        properties: {
          page: {
            margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
          },
        },
        children,
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({ text: 'Generated by ConTigo AI  •  Page ', size: 16, color: '94A3B8' }),
                  new TextRun({ children: [PageNumber.CURRENT], size: 16, color: '94A3B8' }),
                  new TextRun({ text: ' of ', size: 16, color: '94A3B8' }),
                  new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 16, color: '94A3B8' }),
                ],
              }),
            ],
          }),
        },
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  return new Uint8Array(buffer);
}

function renderDocxContent(children: Paragraph[], type: string, data: Record<string, any>) {
  function heading(text: string, level: 1 | 2 = 1) {
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text,
            bold: true,
            size: level === 1 ? 28 : 24,
            color: level === 1 ? '1E293B' : '334155',
            font: 'Calibri',
          }),
        ],
        heading: level === 1 ? HeadingLevel.HEADING_1 : HeadingLevel.HEADING_2,
        spacing: { before: level === 1 ? 400 : 200, after: 100 },
      }),
    );
  }

  function body(text: string) {
    children.push(
      new Paragraph({
        children: [new TextRun({ text: String(text || ''), size: 22, color: '334155', font: 'Calibri' })],
        spacing: { after: 100 },
      }),
    );
  }

  function keyVal(key: string, value: any) {
    if (value == null || value === '') return;
    const valStr = typeof value === 'object' ? JSON.stringify(value) : String(value);
    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: `${key}: `, bold: true, size: 22, color: '64748B', font: 'Calibri' }),
          new TextRun({ text: valStr, size: 22, color: '334155', font: 'Calibri' }),
        ],
        spacing: { after: 60 },
      }),
    );
  }

  function bullet(text: string) {
    children.push(
      new Paragraph({
        children: [new TextRun({ text, size: 22, color: '334155', font: 'Calibri' })],
        bullet: { level: 0 },
        spacing: { after: 40 },
      }),
    );
  }

  // Type-specific rendering
  switch (type) {
    case 'OVERVIEW': {
      const val = (k: string) => data[k]?.value ?? data[k];
      heading('Contract Overview');
      keyVal('Contract Name', val('contractName') || val('title'));
      keyVal('Type', val('contractType'));
      keyVal('Status', data.status);
      keyVal('Effective Date', val('effectiveDate'));
      keyVal('Expiration Date', val('expirationDate'));
      keyVal('Total Value', formatMoney(data.totalValue));
      keyVal('Governing Law', val('governingLaw'));

      if (data.parties?.length) {
        heading('Parties', 2);
        for (const p of data.parties) keyVal(p.role || 'Party', p.name);
      }
      if (val('executiveSummary')) {
        heading('Executive Summary', 2);
        body(val('executiveSummary'));
      }
      break;
    }

    case 'CLAUSES': {
      heading('Key Clauses');
      for (const clause of data.clauses || data.items || []) {
        heading(clause.title || clause.name || 'Clause', 2);
        if (clause.category) keyVal('Category', clause.category);
        if (clause.riskLevel) keyVal('Risk Level', clause.riskLevel);
        body(clause.fullText || clause.text || clause.summary || '');
      }
      break;
    }

    case 'FINANCIAL': {
      heading('Financial Summary');
      keyVal('Total Value', formatMoney(data.totalValue));
      if (data.paymentTerms) {
        heading('Payment Terms', 2);
        if (typeof data.paymentTerms === 'string') {
          body(data.paymentTerms);
        } else {
          keyVal('Net Days', data.paymentTerms.netDays);
          keyVal('Method', data.paymentTerms.paymentMethod);
        }
      }
      if (data.fees?.length) {
        heading('Fees', 2);
        for (const fee of data.fees) {
          bullet(`${fee.name}: ${formatMoney(fee)} (${fee.frequency || 'one-time'})`);
        }
      }
      break;
    }

    case 'RISK': {
      heading('Risk Assessment');
      if (data.overallRiskScore) {
        keyVal('Overall Score', `${data.overallRiskScore.value}/10 (${data.overallRiskScore.category})`);
      }
      for (const risk of data.risks || data.items || []) {
        heading(risk.title || risk.name || 'Risk', 2);
        keyVal('Severity', risk.severity || risk.level);
        keyVal('Category', risk.category);
        body(risk.description || '');
        if (risk.mitigation || risk.recommendation) {
          keyVal('Mitigation', risk.mitigation || risk.recommendation);
        }
      }
      break;
    }

    default: {
      heading(formatArtifactTitle(type));
      for (const [key, value] of Object.entries(data)) {
        if (key === 'extractionMetadata') continue;
        if (Array.isArray(value)) {
          heading(key.replace(/([A-Z])/g, ' $1').trim(), 2);
          for (const item of value.slice(0, 30)) {
            const display = typeof item === 'string'
              ? item
              : item.title || item.name || item.description || JSON.stringify(item);
            bullet(display);
          }
        } else if (typeof value === 'object' && value !== null) {
          keyVal(key, value.value ?? JSON.stringify(value));
        } else {
          keyVal(key, value);
        }
      }
    }
  }
}
