#!/usr/bin/env npx tsx
/**
 * Full E2E Test: realistic_contract.pdf → DI → Azure OpenAI → Artifacts → Chat
 *
 * Tests the complete pipeline end-to-end using the real PDF at public/realistic_contract.pdf:
 *   1. Upload PDF via HTTP API (POST /api/contracts/upload)
 *   2. Poll status until processing completes
 *   3. Verify Azure Document Intelligence OCR extraction
 *   4. Verify all 14 AI artifact types generated by Azure OpenAI
 *   5. Verify contract metadata extracted (parties, dates, values)
 *   6. Test AI chat/RAG endpoint with contract context
 *   7. Report a pass/fail summary with timing
 *
 * ──────────────────────────────────────────────────────────────────────────────
 * USAGE (run against local Docker stack — NOT against production Azure):
 *
 *   # 1. Start local services (postgres + redis + minio)
 *   #    docker compose -f docker-compose.dev.yml up -d postgres redis minio
 *
 *   # 2. Start the Next.js dev/prod app on port 3005
 *   #    docker build -f Dockerfile -t contigo-web-local:latest . && \
 *   #    docker run -d --rm --name contigo-web-local-run --network app_default \
 *   #      -p 3005:3000 --env-file /tmp/container_env.txt contigo-web-local:latest
 *
 *   # 3. Start the OCR worker
 *   #    docker compose -f docker-compose.dev.yml up -d workers
 *
 *   # 4. Run this test
 *   npx tsx scripts/e2e-realistic-contract-test.ts
 *
 *   # Override app URL or test file:
 *   APP_URL=http://localhost:3005 \
 *   TEST_PDF=./public/realistic_contract.pdf \
 *   npx tsx scripts/e2e-realistic-contract-test.ts
 *
 * ──────────────────────────────────────────────────────────────────────────────
 * ⚠️  Always test locally — do NOT run against the production Azure Container App.
 * ──────────────────────────────────────────────────────────────────────────────
 */

import fs from 'fs';
import path from 'path';

// ── Config ────────────────────────────────────────────────────────────────────
const APP_URL = process.env.APP_URL || 'http://localhost:3005';
const TEST_PDF = process.env.TEST_PDF
  ? path.resolve(process.env.TEST_PDF)
  : path.resolve(__dirname, '..', 'public', 'realistic_contract.pdf');

// Use the seeded acme tenant + roberto@acme.com user for auth headers.
// ROBERTO_USER_ID is the cuid assigned to roberto@acme.com by the seed script
// (scripts/seed-comprehensive.ts). Override via USER_ID env var if your seed differs.
const TENANT_ID = process.env.TENANT_ID || 'acme';
const ROBERTO_USER_ID = 'cmltklcyu00039glubwv4g3cx'; // roberto@acme.com — present in all seeded envs
const USER_ID = process.env.USER_ID || ROBERTO_USER_ID;

// Timeouts
const POLL_INTERVAL_MS = 4_000;
const MAX_WAIT_MS = parseInt(process.env.MAX_WAIT_SECONDS || '300', 10) * 1_000; // 5 min default

// All 14 artifact types the pipeline should produce when Azure OpenAI is active
const EXPECTED_ARTIFACT_TYPES = [
  'OVERVIEW',
  'CLAUSES',
  'COMPLIANCE',
  'RISK',
  'FINANCIAL',
  'OBLIGATIONS',
  'RENEWAL',
  'NEGOTIATION_POINTS',
  'AMENDMENTS',
  'CONTACTS',
  'PARTIES',
  'TIMELINE',
  'DELIVERABLES',
  'EXECUTIVE_SUMMARY',
] as const;

// ── Utilities ─────────────────────────────────────────────────────────────────
function log(step: string, msg: string, data?: Record<string, unknown>) {
  const ts = new Date().toISOString().slice(11, 23);
  const extra = data ? '  ' + JSON.stringify(data) : '';
  console.log(`[${ts}] [${step}] ${msg}${extra}`);
}

function hr(char = '═', width = 65) {
  return char.repeat(width);
}

async function sleep(ms: number) {
  return new Promise<void>(resolve => setTimeout(resolve, ms));
}

interface Check {
  name: string;
  pass: boolean;
  detail: string;
  warn?: boolean; // non-blocking — warn but don't fail overall
}

const checks: Check[] = [];

function addCheck(name: string, pass: boolean, detail: string, warn = false) {
  checks.push({ name, pass, detail, warn });
  const icon = pass ? '✅' : warn ? '⚠️ ' : '❌';
  console.log(`  ${icon} ${name}: ${detail}`);
}

// ── Step 1: Health check ──────────────────────────────────────────────────────
async function checkServerHealth(): Promise<void> {
  log('HEALTH', `Checking ${APP_URL}/api/health …`);
  try {
    const res = await fetch(`${APP_URL}/api/health`, { signal: AbortSignal.timeout(10_000) });
    if (res.ok) {
      const body = await res.json().catch(() => ({}));
      addCheck('App server reachable', true, `HTTP ${res.status} — ${JSON.stringify(body).slice(0, 80)}`);
    } else {
      addCheck('App server reachable', false, `HTTP ${res.status}`);
      console.error('\n❌ Server is not healthy. Make sure the local stack is running (see USAGE above).');
      process.exit(1);
    }
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    addCheck('App server reachable', false, message);
    console.error('\n❌ Cannot reach server. Make sure the local stack is running (see USAGE above).');
    process.exit(1);
  }
}

// ── Step 2: Upload PDF ────────────────────────────────────────────────────────
async function uploadPdf(): Promise<string> {
  log('UPLOAD', `Reading ${TEST_PDF} …`);
  if (!fs.existsSync(TEST_PDF)) {
    console.error(`\n❌ PDF not found: ${TEST_PDF}`);
    process.exit(1);
  }
  const buf = fs.readFileSync(TEST_PDF);
  const fileName = path.basename(TEST_PDF);
  log('UPLOAD', `${fileName} — ${(buf.length / 1024).toFixed(1)} KB`);

  // Build multipart/form-data manually (no FormData in older Node)
  const boundary = `----E2ETestBoundary${Date.now()}`;
  const CRLF = '\r\n';
  const head =
    `--${boundary}${CRLF}` +
    `Content-Disposition: form-data; name="file"; filename="${fileName}"${CRLF}` +
    `Content-Type: application/pdf${CRLF}${CRLF}`;
  const tail = `${CRLF}--${boundary}--${CRLF}`;
  const body = Buffer.concat([Buffer.from(head), buf, Buffer.from(tail)]);

  log('UPLOAD', `POST ${APP_URL}/api/contracts/upload`);
  const res = await fetch(`${APP_URL}/api/contracts/upload`, {
    method: 'POST',
    headers: {
      'Content-Type': `multipart/form-data; boundary=${boundary}`,
      'x-tenant-id': TENANT_ID,
      'x-user-id': USER_ID,
      'x-skip-duplicate-check': 'true',
    },
    body,
    signal: AbortSignal.timeout(60_000),
  });

  const text = await res.text();
  if (!res.ok) {
    addCheck('PDF upload', false, `HTTP ${res.status} — ${text.slice(0, 200)}`);
    console.error('\n❌ Upload failed.');
    process.exit(1);
  }

  let data: Record<string, unknown>;
  try {
    data = JSON.parse(text);
  } catch {
    addCheck('PDF upload', false, `Non-JSON response: ${text.slice(0, 100)}`);
    process.exit(1);
  }

  const contractId = (data.contractId as string) || (data.id as string);
  if (!contractId) {
    addCheck('PDF upload', false, `No contractId in response: ${JSON.stringify(data).slice(0, 200)}`);
    process.exit(1);
  }

  addCheck('PDF upload', true, `contractId=${contractId}`);
  return contractId;
}

// ── Step 3: Poll until complete ───────────────────────────────────────────────
interface ContractStatus {
  contractId?: string;
  status: string;
  currentStep?: string;
  progress?: number;
  artifactsGenerated?: number;
  totalArtifacts?: number;
  error?: string;
}

async function pollUntilComplete(contractId: string): Promise<ContractStatus> {
  log('POLL', `Waiting for processing to complete (max ${MAX_WAIT_MS / 1000}s) …`);
  const start = Date.now();
  let lastStep = '';
  let lastProgress = -1;

  while (Date.now() - start < MAX_WAIT_MS) {
    await sleep(POLL_INTERVAL_MS);

    let status: ContractStatus;
    try {
      const res = await fetch(`${APP_URL}/api/contracts/${contractId}/status`, {
        headers: { 'x-tenant-id': TENANT_ID, 'x-user-id': USER_ID },
        signal: AbortSignal.timeout(10_000),
      });
      if (!res.ok) {
        process.stdout.write('.');
        continue;
      }
      status = await res.json();
    } catch {
      process.stdout.write('.');
      continue;
    }

    const progress = status.progress ?? 0;
    const step = status.currentStep || status.status || '';
    const elapsed = ((Date.now() - start) / 1000).toFixed(0);

    if (step !== lastStep || Math.abs(progress - lastProgress) >= 5) {
      process.stdout.write('\n');
      log('POLL', `${progress}% | ${step}`, { elapsed: `${elapsed}s` });
      lastStep = step;
      lastProgress = progress;
    } else {
      process.stdout.write('.');
    }

    const upper = (status.status || '').toUpperCase();
    if (upper === 'COMPLETED' || upper === 'ACTIVE') {
      process.stdout.write('\n');
      log('POLL', `✅ Completed in ${elapsed}s`);
      return status;
    }
    if (upper === 'FAILED') {
      process.stdout.write('\n');
      log('POLL', `❌ Processing failed`, { error: status.error });
      addCheck('Processing completed', false, `Status=FAILED — ${status.error || 'unknown error'}`);
      return status;
    }
  }

  process.stdout.write('\n');
  const elapsed = ((Date.now() - start) / 1000).toFixed(0);
  addCheck('Processing completed', false, `Timed out after ${elapsed}s — still in ${lastStep}`);
  return { status: 'TIMEOUT' };
}

// ── Step 4: Verify DI OCR extraction ─────────────────────────────────────────
interface ContractDetails {
  id: string;
  status: string;
  rawText?: string;
  searchableText?: string;
  ocrProvider?: string;
  ocrModel?: string;
  ocrProcessedAt?: string;
  contractType?: string;
  contractTitle?: string;
  supplierName?: string;
  clientName?: string;
  startDate?: string;
  endDate?: string;
  totalValue?: number | string;
  signatureStatus?: string;
  signatureRequiredFlag?: boolean;
  artifacts?: ArtifactRecord[];
}

interface ArtifactRecord {
  id: string;
  type: string;
  data: Record<string, unknown>;
  validationStatus?: string;
  createdAt?: string;
}

async function fetchContractDetails(contractId: string): Promise<ContractDetails> {
  const res = await fetch(`${APP_URL}/api/contracts/${contractId}`, {
    headers: { 'x-tenant-id': TENANT_ID, 'x-user-id': USER_ID },
    signal: AbortSignal.timeout(15_000),
  });
  if (!res.ok) {
    throw new Error(`GET /api/contracts/${contractId} returned HTTP ${res.status}`);
  }
  const body = await res.json();
  // API wraps in { contract: {...} } or returns directly
  return (body.contract || body) as ContractDetails;
}

function verifyOcrExtraction(contract: ContractDetails) {
  console.log('\n' + hr('-'));
  console.log('OCR / Document Intelligence Extraction');
  console.log(hr('-'));

  const rawLen = contract.rawText?.length ?? 0;
  addCheck(
    'OCR text extracted (rawText)',
    rawLen > 100,
    rawLen > 0 ? `${rawLen} chars — preview: "${(contract.rawText || '').slice(0, 80).replace(/\n/g, ' ')}…"` : 'empty',
  );

  addCheck(
    'OCR provider = Azure Document Intelligence',
    contract.ocrProvider === 'azure-document-intelligence',
    contract.ocrProvider || 'not set',
    // warn if not set yet (may still be in flight)
    !contract.ocrProvider,
  );

  addCheck(
    'OCR model recorded',
    !!contract.ocrModel,
    contract.ocrModel || 'not set',
    !contract.ocrModel,
  );

  addCheck(
    'OCR processed timestamp',
    !!contract.ocrProcessedAt,
    contract.ocrProcessedAt || 'not set',
    !contract.ocrProcessedAt,
  );
}

// ── Step 5: Verify artifact generation ───────────────────────────────────────
async function fetchArtifacts(contractId: string): Promise<ArtifactRecord[]> {
  const res = await fetch(`${APP_URL}/api/contracts/${contractId}/artifacts`, {
    headers: { 'x-tenant-id': TENANT_ID, 'x-user-id': USER_ID },
    signal: AbortSignal.timeout(15_000),
  });
  if (!res.ok) return [];
  const body = await res.json();
  return Array.isArray(body) ? body : (body.artifacts ?? []);
}

function verifyArtifacts(artifacts: ArtifactRecord[]) {
  console.log('\n' + hr('-'));
  console.log('AI Artifact Generation (14 types expected)');
  console.log(hr('-'));

  addCheck(
    'Artifacts returned',
    artifacts.length > 0,
    `${artifacts.length} artifact(s)`,
  );

  const byType = new Map(artifacts.map(a => [a.type, a]));

  for (const type of EXPECTED_ARTIFACT_TYPES) {
    const art = byType.get(type);
    if (!art) {
      addCheck(`Artifact: ${type}`, false, 'missing');
      continue;
    }
    const dataKeys = Object.keys(art.data || {}).filter(k => !k.startsWith('_'));
    const isAI = (art.data as Record<string, unknown>)?._mode !== 'basic';
    addCheck(
      `Artifact: ${type}`,
      dataKeys.length > 0,
      `${dataKeys.length} data fields${isAI ? '' : ' (basic/regex mode — Azure OpenAI may not be connected)'}`,
      !isAI,
    );
  }
}

// ── Step 6: Verify metadata extraction ───────────────────────────────────────
function verifyMetadata(contract: ContractDetails) {
  console.log('\n' + hr('-'));
  console.log('Contract Metadata Extraction');
  console.log(hr('-'));

  addCheck(
    'Contract type detected',
    !!contract.contractType && contract.contractType !== 'UNKNOWN',
    contract.contractType || 'not set',
    !contract.contractType,
  );

  addCheck(
    'Contract title extracted',
    !!contract.contractTitle,
    contract.contractTitle || 'not set',
    !contract.contractTitle,
  );

  addCheck(
    'Supplier / vendor name',
    !!contract.supplierName,
    contract.supplierName || 'not set',
    !contract.supplierName,
  );

  addCheck(
    'Client / buyer name',
    !!contract.clientName,
    contract.clientName || 'not set',
    !contract.clientName,
  );

  addCheck(
    'Start date extracted',
    !!contract.startDate,
    contract.startDate ? new Date(contract.startDate).toLocaleDateString() : 'not set',
    !contract.startDate,
  );

  addCheck(
    'End date extracted',
    !!contract.endDate,
    contract.endDate ? new Date(contract.endDate).toLocaleDateString() : 'not set',
    !contract.endDate,
  );

  addCheck(
    'Signature status detected',
    !!contract.signatureStatus,
    contract.signatureStatus || 'not set',
    !contract.signatureStatus,
  );
}

// ── Step 7: Test chat / RAG ───────────────────────────────────────────────────
async function testChatRag(contractId: string) {
  console.log('\n' + hr('-'));
  console.log('Chat / RAG Endpoint');
  console.log(hr('-'));

  log('CHAT', `POST ${APP_URL}/api/ai/chat/stream`);
  try {
    const res = await fetch(`${APP_URL}/api/ai/chat/stream`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-tenant-id': TENANT_ID,
        'x-user-id': USER_ID,
      },
      body: JSON.stringify({
        message: 'What are the key parties and the total contract value in this agreement?',
        conversationHistory: [],
        context: { contractId },
      }),
      signal: AbortSignal.timeout(60_000),
    });

    if (!res.ok) {
      const text = await res.text();
      addCheck('Chat endpoint responds', false, `HTTP ${res.status} — ${text.slice(0, 150)}`);
      return;
    }

    // Consume SSE stream and look for a content event
    const text = await res.text();
    const hasContent = text.includes('"type":"content"') || text.includes('"content"');
    const hasMetadata = text.includes('"type":"metadata"');
    const hasError = text.includes('"type":"error"');
    const hasDone = text.includes('"type":"done"');

    addCheck(
      'Chat endpoint responds',
      res.ok,
      `HTTP ${res.status}`,
    );
    addCheck(
      'Chat SSE metadata event received',
      hasMetadata,
      hasMetadata ? 'yes' : 'missing',
      !hasMetadata,
    );
    addCheck(
      'Chat SSE content/error event received',
      hasContent || hasError,
      hasContent ? 'content event ✓' : hasError ? 'error event (Azure OpenAI may not be configured)' : 'no content',
      hasError || (!hasContent && !hasError),
    );
    addCheck(
      'Chat SSE done event received',
      hasDone,
      hasDone ? 'yes' : 'missing',
      !hasDone,
    );

    // Print first 300 chars of the response for debugging
    if (process.env.VERBOSE) {
      console.log('\n  Raw SSE response (first 300 chars):');
      console.log('  ' + text.slice(0, 300).replace(/\n/g, '\n  '));
    }
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    addCheck('Chat endpoint responds', false, message);
  }
}

// ── Main ──────────────────────────────────────────────────────────────────────
async function main() {
  const testStart = Date.now();

  console.log('\n' + hr());
  console.log('  E2E Test: realistic_contract.pdf → DI → Azure OpenAI → Chat');
  console.log(hr());
  console.log(`  App URL  : ${APP_URL}`);
  console.log(`  PDF      : ${TEST_PDF}`);
  console.log(`  Tenant   : ${TENANT_ID}`);
  console.log(`  User     : ${USER_ID}`);
  console.log(hr());
  console.log('  ⚠️  Run this against your LOCAL Docker stack, not production!');
  console.log(hr() + '\n');

  // ── 1. Health ──────────────────────────────────────────────────────────────
  console.log('\n' + hr('-'));
  console.log('Step 1 — Server Health');
  console.log(hr('-'));
  await checkServerHealth();

  // ── 2. Upload ──────────────────────────────────────────────────────────────
  console.log('\n' + hr('-'));
  console.log('Step 2 — PDF Upload');
  console.log(hr('-'));
  const contractId = await uploadPdf();

  // ── 3. Poll ────────────────────────────────────────────────────────────────
  console.log('\n' + hr('-'));
  console.log('Step 3 — Processing Pipeline (DI OCR + Azure OpenAI Artifacts)');
  console.log(hr('-'));
  const finalStatus = await pollUntilComplete(contractId);
  const processingOk = ['COMPLETED', 'ACTIVE'].includes((finalStatus.status || '').toUpperCase());
  addCheck(
    'Processing completed',
    processingOk,
    `Final status: ${finalStatus.status}`,
  );

  if (!processingOk) {
    console.log('\n⚠️  Processing did not complete — remaining checks use whatever data is available.\n');
  }

  // ── 4. Fetch details & verify ──────────────────────────────────────────────
  let contract: ContractDetails | null = null;
  try {
    contract = await fetchContractDetails(contractId);
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    addCheck('Fetch contract details', false, message);
  }

  if (contract) {
    verifyOcrExtraction(contract);
    verifyMetadata(contract);
  }

  // ── 5. Artifacts ───────────────────────────────────────────────────────────
  const artifacts = await fetchArtifacts(contractId);
  verifyArtifacts(artifacts);

  // ── 6. Chat ────────────────────────────────────────────────────────────────
  await testChatRag(contractId);

  // ── Summary ────────────────────────────────────────────────────────────────
  const elapsed = ((Date.now() - testStart) / 1000).toFixed(1);
  const hardFails = checks.filter(c => !c.pass && !c.warn);
  const warns = checks.filter(c => !c.pass && c.warn);
  const passed = checks.filter(c => c.pass);

  console.log('\n' + hr());
  console.log('  SUMMARY');
  console.log(hr());
  console.log(`  ✅ Passed  : ${passed.length}`);
  console.log(`  ⚠️  Warnings: ${warns.length}  (non-blocking)`);
  console.log(`  ❌ Failed  : ${hardFails.length}`);
  console.log(`  ⏱  Total   : ${elapsed}s`);
  console.log(`  📄 Contract: ${contractId}`);
  console.log(`  🌐 View at : ${APP_URL}/contracts/${contractId}`);

  if (warns.length) {
    console.log('\n  Warnings (usually mean Azure OpenAI deployment not yet active):');
    warns.forEach(w => console.log(`    ⚠️  ${w.name}: ${w.detail}`));
  }
  if (hardFails.length) {
    console.log('\n  Failures:');
    hardFails.forEach(f => console.log(`    ❌ ${f.name}: ${f.detail}`));
  }

  console.log('\n' + hr());
  if (hardFails.length === 0) {
    console.log('  ✅ ALL HARD CHECKS PASSED');
  } else {
    console.log(`  ❌ ${hardFails.length} HARD CHECK(S) FAILED`);
  }
  console.log(hr() + '\n');

  process.exit(hardFails.length === 0 ? 0 : 1);
}

main().catch(err => {
  console.error('\n💥 Unexpected error:', err);
  process.exit(1);
});
