/**
 * Enhanced Contracts Page Demo
 * 
 * This page demonstrates all the new UI/UX components for the contracts page.
 * Use this as a reference for integrating the enhanced components into the main contracts page.
 * 
 * Features:
 * - Hero Dashboard with stats and trends
 * - Smart Filters with AI-powered suggestions
 * - Enhanced Contract Cards with health indicators
 * - Contract Preview Panel (email-app style)
 * - Floating Bulk Actions Bar
 * - Mobile-optimized views with swipe gestures
 * 
 * @author Generated by AI Assistant
 * @version 2.0.0
 */

"use client";

import { useState, useMemo, useCallback, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { PageBreadcrumb } from "@/components/navigation";
import { Button } from "@/components/ui/button";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import {
  LayoutGrid,
  LayoutList,
  GanttChartSquare,
  RefreshCw,
  Upload,
  Plus,
  FileText,
  AlertTriangle,
} from "lucide-react";

// Import enhanced components
import { ContractsHeroDashboard, type ContractStats } from "@/components/contracts/ContractsHeroDashboard";
import { 
  EnhancedContractCard, 
  EnhancedContractRow,
  type EnhancedContract 
} from "@/components/contracts/EnhancedContractCard";
import { ContractPreviewPanel, type ExtendedContract } from "@/components/contracts/ContractPreviewPanel";
import { EnhancedBulkActionsBar, type BulkAction, type BulkActionType } from "@/components/contracts/EnhancedBulkActionsBar";
import { SmartFilters, type ContractFilters } from "@/components/contracts/SmartFilters";
import {
  MobileContractCard,
  MobileSearchBar,
  MobileFiltersSheet,
  MobilePullToRefresh,
  MobileStatsSummary,
  MobileEmptyState,
  MobileFAB,
} from "@/components/contracts/MobileContractViews";
import { cn } from "@/lib/utils";

// ============================================================================
// Mock Data for Demo
// ============================================================================

const MOCK_STATS: ContractStats = {
  totalContracts: 247,
  totalValue: 15750000,
  expiringSoon: 12,
  highRisk: 5,
  activeContracts: 189,
  pendingReview: 23,
  recentlyAdded: 15,
  avgRiskScore: 35,
  trends: {
    contracts: 12.5,
    value: 8.3,
    risk: -5.2,
  },
  trendData: [
    { date: "Jan", contracts: 220, value: 12500000 },
    { date: "Feb", contracts: 228, value: 13200000 },
    { date: "Mar", contracts: 235, value: 14100000 },
    { date: "Apr", contracts: 240, value: 15000000 },
    { date: "May", contracts: 247, value: 15750000 },
  ],
};

const MOCK_CONTRACTS: EnhancedContract[] = [
  {
    id: "1",
    title: "Master Service Agreement - Acme Corp",
    type: "Master Service Agreement",
    status: "active",
    value: 2500000,
    currency: "USD",
    startDate: "2024-01-15",
    endDate: "2025-01-15",
    parties: [
      { id: "p1", name: "Acme Corporation", role: "client" },
      { id: "p2", name: "TechVentures Inc", role: "vendor" },
    ],
    health: { score: 92, riskLevel: "low", issues: [] },
    isPinned: true,
    isFavorite: false,
    lastModified: "2024-12-15T10:30:00Z",
    tags: ["Enterprise", "Priority", "Renewable"],
    completeness: 95,
    hasAttachments: true,
    attachmentCount: 5,
    description: "Comprehensive master service agreement covering all IT consulting services.",
  },
  {
    id: "2",
    title: "Software License Agreement - DataFlow",
    type: "Software License",
    status: "pending",
    value: 450000,
    currency: "USD",
    startDate: "2024-12-01",
    endDate: "2025-11-30",
    parties: [
      { id: "p3", name: "DataFlow Systems", role: "vendor" },
    ],
    health: { score: 68, riskLevel: "medium", issues: ["Missing liability clause", "Unclear termination terms"] },
    isPinned: false,
    isFavorite: true,
    lastModified: "2024-12-18T14:22:00Z",
    tags: ["Software", "Annual"],
    completeness: 75,
    hasAttachments: true,
    attachmentCount: 2,
    description: "Annual software licensing for data analytics platform.",
  },
  {
    id: "3",
    title: "Consulting Agreement - Strategic Partners",
    type: "Consulting Agreement",
    status: "renewal",
    value: 180000,
    currency: "USD",
    startDate: "2024-03-01",
    endDate: "2025-01-10",
    parties: [
      { id: "p4", name: "Strategic Partners LLC", role: "vendor" },
      { id: "p5", name: "Our Company", role: "client" },
    ],
    health: { score: 45, riskLevel: "high", issues: ["Expiring in 25 days", "No auto-renewal clause", "Missing performance metrics"] },
    isPinned: false,
    isFavorite: false,
    lastModified: "2024-12-10T09:15:00Z",
    tags: ["Consulting", "Urgent"],
    completeness: 88,
    hasAttachments: false,
    attachmentCount: 0,
    description: "Strategic consulting services for market expansion.",
  },
  {
    id: "4",
    title: "NDA - Confidential Project Alpha",
    type: "Non-Disclosure Agreement",
    status: "active",
    value: 0,
    parties: [
      { id: "p6", name: "Alpha Technologies", role: "partner" },
    ],
    health: { score: 100, riskLevel: "low" },
    isPinned: false,
    isFavorite: false,
    lastModified: "2024-11-20T16:45:00Z",
    tags: ["NDA", "Confidential"],
    completeness: 100,
    hasAttachments: true,
    attachmentCount: 1,
  },
  {
    id: "5",
    title: "Equipment Lease Agreement",
    type: "Lease Agreement",
    status: "draft",
    value: 75000,
    currency: "USD",
    parties: [
      { id: "p7", name: "Industrial Equipment Co", role: "vendor" },
    ],
    health: { score: 30, riskLevel: "critical", issues: ["Incomplete draft", "Missing financial terms", "No signatures"] },
    isPinned: false,
    isFavorite: false,
    lastModified: "2024-12-19T11:00:00Z",
    tags: ["Draft", "Equipment"],
    completeness: 35,
    hasAttachments: false,
    attachmentCount: 0,
    description: "Draft agreement for heavy machinery lease.",
  },
  {
    id: "6",
    title: "Cloud Infrastructure Services",
    type: "Service Agreement",
    status: "active",
    value: 890000,
    currency: "USD",
    startDate: "2024-06-01",
    endDate: "2026-05-31",
    parties: [
      { id: "p8", name: "CloudScale Inc", role: "vendor" },
    ],
    health: { score: 85, riskLevel: "low" },
    isPinned: true,
    isFavorite: true,
    lastModified: "2024-12-01T08:30:00Z",
    tags: ["Cloud", "Infrastructure", "Priority"],
    completeness: 100,
    hasAttachments: true,
    attachmentCount: 8,
    description: "Multi-year cloud infrastructure and support agreement.",
  },
];

const AVAILABLE_TAGS = [
  "Enterprise",
  "Priority",
  "Renewable",
  "Software",
  "Annual",
  "Consulting",
  "Urgent",
  "NDA",
  "Confidential",
  "Draft",
  "Equipment",
  "Cloud",
  "Infrastructure",
];

const SEARCH_SUGGESTIONS = [
  "agreements expiring this month",
  "high value active contracts",
  "master service agreements",
  "contracts with Acme Corp",
  "pending review items",
  "renewable contracts",
];

// ============================================================================
// Main Component
// ============================================================================

export default function EnhancedContractsDemo() {
  const router = useRouter();

  // View state
  const [viewMode, setViewMode] = useState<"list" | "grid" | "timeline">("grid");
  const [isMobile, setIsMobile] = useState(false);
  const [mobileStatsExpanded, setMobileStatsExpanded] = useState(false);

  // Filters state
  const [filters, setFilters] = useState<ContractFilters>({});
  const [mobileFiltersOpen, setMobileFiltersOpen] = useState(false);
  const [isLoading, setIsLoading] = useState(false);

  // Selection state
  const [selectedIds, setSelectedIds] = useState<string[]>([]);

  // Preview panel state
  const [previewContract, setPreviewContract] = useState<ExtendedContract | null>(null);
  const [previewOpen, setPreviewOpen] = useState(false);

  // Contracts data
  const [contracts, setContracts] = useState<EnhancedContract[]>(MOCK_CONTRACTS);

  // Check for mobile viewport
  useEffect(() => {
    const checkMobile = () => setIsMobile(window.innerWidth < 768);
    checkMobile();
    window.addEventListener("resize", checkMobile);
    return () => window.removeEventListener("resize", checkMobile);
  }, []);

  // Filter contracts based on current filters
  const filteredContracts = useMemo(() => {
    return contracts.filter((contract) => {
      // Search filter
      if (filters.search) {
        const search = filters.search.toLowerCase();
        if (
          !(contract.title || '').toLowerCase().includes(search) &&
          !(contract.type || '').toLowerCase().includes(search)
        ) {
          return false;
        }
      }

      // Status filter
      if (filters.status?.length && contract.status && !filters.status.includes(contract.status)) {
        return false;
      }

      // Risk filter
      if (filters.riskLevel?.length && contract.health?.riskLevel) {
        if (!filters.riskLevel.includes(contract.health.riskLevel)) {
          return false;
        }
      }

      // Favorites filter
      if (filters.isFavorite && !contract.isFavorite) {
        return false;
      }

      // Pinned filter
      if (filters.isPinned && !contract.isPinned) {
        return false;
      }

      // Tags filter
      if (filters.tags?.length) {
        if (!contract.tags?.some((tag) => filters.tags!.includes(tag))) {
          return false;
        }
      }

      return true;
    });
  }, [contracts, filters]);

  // Handlers
  const handleSelectContract = useCallback((id: string, selected: boolean) => {
    setSelectedIds((prev) =>
      selected ? [...prev, id] : prev.filter((i) => i !== id)
    );
  }, []);

  const handleSelectAll = useCallback(() => {
    setSelectedIds(filteredContracts.map((c) => c.id));
  }, [filteredContracts]);

  const handleDeselectAll = useCallback(() => {
    setSelectedIds([]);
  }, []);

  const handleContractClick = useCallback((id: string) => {
    const contract = contracts.find((c) => c.id === id);
    if (contract) {
      // Convert to ExtendedContract for preview
      const extended: ExtendedContract = {
        ...contract,
        clauses: [
          {
            id: "c1",
            title: "Limitation of Liability",
            section: "Section 8",
            riskLevel: "medium",
            summary: "Liability capped at total contract value.",
          },
          {
            id: "c2",
            title: "Termination",
            section: "Section 12",
            riskLevel: "low",
            summary: "30-day notice required for termination.",
          },
        ],
        activities: [
          {
            id: "a1",
            type: "created",
            description: "Contract created",
            timestamp: contract.createdAt || new Date().toISOString(),
            user: { name: "John Doe" },
          },
          {
            id: "a2",
            type: "ai_analysis",
            description: "AI analysis completed",
            timestamp: new Date().toISOString(),
            user: { name: "AI System" },
          },
        ],
        keyTerms: [
          { label: "Payment Terms", value: "Net 30" },
          { label: "Renewal", value: "Auto-renewable" },
          { label: "Jurisdiction", value: "Delaware, USA" },
        ],
      };
      setPreviewContract(extended);
      setPreviewOpen(true);
    }
  }, [contracts]);

  const handlePreviewNavigate = useCallback(
    (direction: "prev" | "next") => {
      if (!previewContract) return;
      const currentIndex = filteredContracts.findIndex((c) => c.id === previewContract.id);
      const newIndex =
        direction === "prev"
          ? Math.max(0, currentIndex - 1)
          : Math.min(filteredContracts.length - 1, currentIndex + 1);
      const newContract = filteredContracts[newIndex];
      if (newContract && newContract.id !== previewContract.id) {
        handleContractClick(newContract.id);
      }
    },
    [previewContract, filteredContracts, handleContractClick]
  );

  const handleQuickAction = useCallback((action: string) => {
    toast.info(`Quick action: ${action}`);
    if (action === "upload") {
      router.push("/upload");
    } else if (action === "generate") {
      router.push("/generate-contract");
    } else if (action === "compare") {
      toast.info("Opening contract comparison...");
    }
  }, [router]);

  const handleBulkAction = useCallback(
    async (action: BulkAction | BulkActionType, params?: Record<string, any>) => {
      setIsLoading(true);
      try {
        // Simulate API call
        await new Promise((resolve) => setTimeout(resolve, 1000));
        
        const actionId = typeof action === 'string' ? action : action.id;
        switch (actionId) {
          case "delete":
            setContracts((prev) => prev.filter((c) => !selectedIds.includes(c.id)));
            toast.success(`Deleted ${selectedIds.length} contracts`);
            setSelectedIds([]);
            break;
          case "analyze":
            toast.success(`AI analysis started for ${selectedIds.length} contracts`);
            break;
          case "export":
            toast.success(`Exporting ${selectedIds.length} contracts as ${params?.format || "PDF"}`);
            break;
          case "tag":
            toast.success(`Tags updated for ${selectedIds.length} contracts`);
            break;
          case "favorite":
            setContracts((prev) =>
              prev.map((c) =>
                selectedIds.includes(c.id) ? { ...c, isFavorite: true } : c
              )
            );
            toast.success(`Favorited ${selectedIds.length} contracts`);
            break;
          case "pin":
            setContracts((prev) =>
              prev.map((c) =>
                selectedIds.includes(c.id) ? { ...c, isPinned: true } : c
              )
            );
            toast.success(`Pinned ${selectedIds.length} contracts`);
            break;
          default:
            toast.info(`Action: ${actionId}`);
        }

        return { success: selectedIds.length, failed: 0 };
      } finally {
        setIsLoading(false);
      }
    },
    [selectedIds]
  );

  const handlePinToggle = useCallback((id: string) => {
    setContracts((prev) =>
      prev.map((c) => (c.id === id ? { ...c, isPinned: !c.isPinned } : c))
    );
  }, []);

  const handleFavoriteToggle = useCallback((id: string) => {
    setContracts((prev) =>
      prev.map((c) => (c.id === id ? { ...c, isFavorite: !c.isFavorite } : c))
    );
  }, []);

  const handleRefresh = async () => {
    setIsLoading(true);
    await new Promise((resolve) => setTimeout(resolve, 1000));
    setIsLoading(false);
    toast.success("Contracts refreshed");
  };

  // Mobile view
  if (isMobile) {
    return (
      <div className="min-h-screen bg-gray-50 pb-20">
        <div className="mb-4 flex items-center gap-2 rounded-lg border border-amber-200 bg-amber-50 px-4 py-2 text-sm text-amber-700 dark:border-amber-800 dark:bg-amber-950 dark:text-amber-300">
          <AlertTriangle className="h-4 w-4 shrink-0" />
          <span>Preview Mode — data shown is illustrative. Full integration is under development.</span>
        </div>
        {/* Mobile Search Bar */}
        <MobileSearchBar
          value={filters.search || ""}
          onChange={(value) => setFilters({ ...filters, search: value || undefined })}
          onFilterClick={() => setMobileFiltersOpen(true)}
          activeFilterCount={Object.keys(filters).filter((k) => filters[k as keyof ContractFilters]).length}
        />

        {/* Mobile Stats Summary */}
        <div className="py-4">
          <MobileStatsSummary
            stats={{
              total: MOCK_STATS.totalContracts ?? 0,
              active: MOCK_STATS.activeContracts ?? 0,
              expiringSoon: MOCK_STATS.expiringSoon ?? 0,
              highRisk: MOCK_STATS.highRisk ?? 0,
              totalValue: MOCK_STATS.totalValue ?? 0,
            }}
            isExpanded={mobileStatsExpanded}
            onToggle={() => setMobileStatsExpanded(!mobileStatsExpanded)}
          />
        </div>

        {/* Contract List */}
        <MobilePullToRefresh onRefresh={handleRefresh}>
          <div className="px-4 space-y-3 pb-4">
            {filteredContracts.length === 0 ? (
              <MobileEmptyState
                title="No contracts found"
                description="Try adjusting your filters or upload a new contract"
                action={{
                  label: "Upload Contract",
                  onClick: () => router.push("/upload"),
                }}
              />
            ) : (
              filteredContracts.map((contract) => (
                <MobileContractCard
                  key={contract.id}
                  contract={contract}
                  isSelected={selectedIds.includes(contract.id)}
                  onSelect={handleSelectContract}
                  onClick={handleContractClick}
                  onSwipeAction={(id, action) => {
                    if (action === "favorite") handleFavoriteToggle(id);
                    if (action === "delete") {
                      setContracts((prev) => prev.filter((c) => c.id !== id));
                      toast.success("Contract deleted");
                    }
                  }}
                />
              ))
            )}
          </div>
        </MobilePullToRefresh>

        {/* Mobile FAB */}
        <MobileFAB onClick={() => router.push("/upload")} />

        {/* Mobile Filters Sheet */}
        <MobileFiltersSheet
          isOpen={mobileFiltersOpen}
          onOpenChange={setMobileFiltersOpen}
          filters={filters}
          onFiltersChange={setFilters}
          onApply={() => setMobileFiltersOpen(false)}
          onReset={() => setFilters({})}
          availableTags={AVAILABLE_TAGS}
          resultCount={filteredContracts.length}
        />

        {/* Bulk Actions */}
        <EnhancedBulkActionsBar
          selectedCount={selectedIds.length}
          totalCount={filteredContracts.length}
          selectedIds={selectedIds}
          onSelectAll={handleSelectAll}
          onDeselectAll={handleDeselectAll}
          onAction={handleBulkAction}
          availableTags={AVAILABLE_TAGS}
          isLoading={isLoading}
        />
      </div>
    );
  }

  // Desktop view
  return (
    <div className="min-h-screen bg-slate-50">
      {/* Header */}
      <div className="bg-white border-b border-slate-200">
        <div className="max-w-[1600px] mx-auto px-6 sm:px-8 lg:px-12 py-6">
          <PageBreadcrumb />

          <div className="mt-4 flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4">
            <div>
              <div className="flex items-center gap-2.5 mb-1">
                <FileText className="h-6 w-6 text-slate-700" />
                <h1 className="text-2xl font-semibold text-slate-900">
                  Contracts
                  <span className="ml-2 text-sm font-normal text-violet-600 bg-violet-50 px-2 py-0.5 rounded-full">
                    Enhanced UI Demo
                  </span>
                </h1>
              </div>
              <p className="text-slate-500 text-sm">
                Showcasing the new UI/UX components for the contracts page
              </p>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" onClick={handleRefresh} className="h-9">
                <RefreshCw className={cn("h-4 w-4 mr-1.5", isLoading && "animate-spin")} />
                Refresh
              </Button>
              <Button asChild size="sm" className="bg-violet-600 hover:bg-violet-700 text-white h-9">
                <a href="/upload">
                  <Upload className="h-4 w-4 mr-1.5" />
                  Upload Contract
                </a>
              </Button>
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-[1600px] mx-auto px-6 sm:px-8 lg:px-12 py-6 space-y-6">
        <div className="mb-4 flex items-center gap-2 rounded-lg border border-amber-200 bg-amber-50 px-4 py-2 text-sm text-amber-700 dark:border-amber-800 dark:bg-amber-950 dark:text-amber-300">
          <AlertTriangle className="h-4 w-4 shrink-0" />
          <span>Preview Mode — data shown is illustrative. Full integration is under development.</span>
        </div>

        {/* Hero Dashboard */}
        <ContractsHeroDashboard
          stats={MOCK_STATS}
          isLoading={isLoading}
          onQuickAction={handleQuickAction}
        />

        {/* Smart Filters */}
        <SmartFilters
          filters={filters}
          onFiltersChange={setFilters}
          availableTags={AVAILABLE_TAGS}
          searchSuggestions={SEARCH_SUGGESTIONS}
          resultCount={filteredContracts.length}
          isLoading={isLoading}
        />

        {/* View Mode Switcher */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2 bg-gray-100 rounded-lg p-1">
            <Button
              variant={viewMode === "grid" ? "default" : "ghost"}
              size="sm"
              onClick={() => setViewMode("grid")}
              className="h-8"
            >
              <LayoutGrid className="w-4 h-4 mr-1.5" />
              Grid
            </Button>
            <Button
              variant={viewMode === "list" ? "default" : "ghost"}
              size="sm"
              onClick={() => setViewMode("list")}
              className="h-8"
            >
              <LayoutList className="w-4 h-4 mr-1.5" />
              List
            </Button>
            <Button
              variant={viewMode === "timeline" ? "default" : "ghost"}
              size="sm"
              onClick={() => setViewMode("timeline")}
              className="h-8"
            >
              <GanttChartSquare className="w-4 h-4 mr-1.5" />
              Timeline
            </Button>
          </div>

          <p className="text-sm text-muted-foreground">
            Showing {filteredContracts.length} of {contracts.length} contracts
          </p>
        </div>

        {/* Contracts Display */}
        <AnimatePresence mode="wait">
          {filteredContracts.length === 0 ? (
            <motion.div
              key="empty"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="py-16 text-center"
            >
              <FileText className="w-16 h-16 mx-auto text-gray-300 mb-4" />
              <h3 className="text-lg font-semibold text-gray-900 mb-2">No contracts found</h3>
              <p className="text-muted-foreground mb-6">
                Try adjusting your filters or upload a new contract
              </p>
              <Button onClick={() => router.push("/upload")}>
                <Plus className="w-4 h-4 mr-2" />
                Upload Contract
              </Button>
            </motion.div>
          ) : viewMode === "grid" ? (
            <motion.div
              key="grid"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4"
            >
              {filteredContracts.map((contract) => (
                <EnhancedContractCard
                  key={contract.id}
                  contract={contract}
                  isSelected={selectedIds.includes(contract.id)}
                  onSelect={(id, selected) => id && handleSelectContract(id, selected ?? false)}
                  onClick={(id) => id && handleContractClick(id)}
                  onPin={handlePinToggle}
                  onFavorite={handleFavoriteToggle}
                  onPreview={(id) => handleContractClick(id)}
                  onAnalyze={(id) => toast.info(`AI analyzing contract ${id}...`)}
                  onEdit={(id) => router.push(`/contracts/${id}`)}
                  onDelete={(id) => {
                    setContracts((prev) => prev.filter((c) => c.id !== id));
                    toast.success("Contract deleted");
                  }}
                />
              ))}
            </motion.div>
          ) : viewMode === "list" ? (
            <motion.div
              key="list"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="bg-white rounded-xl border overflow-hidden"
            >
              {/* List Header */}
              <div className="grid grid-cols-[40px_1fr_160px_120px_100px_100px_80px_60px] gap-4 px-4 py-3 bg-gray-50 border-b text-xs font-medium text-gray-500">
                <div></div>
                <div>Contract</div>
                <div className="hidden lg:block">Parties</div>
                <div className="hidden md:block">Value</div>
                <div className="hidden md:block">End Date</div>
                <div>Status</div>
                <div>Health</div>
                <div></div>
              </div>

              {/* List Items */}
              {filteredContracts.map((contract) => (
                <EnhancedContractRow
                  key={contract.id}
                  contract={contract}
                  isSelected={selectedIds.includes(contract.id)}
                  onSelect={(id, selected) => id && handleSelectContract(id, selected ?? false)}
                  onClick={(id) => id && handleContractClick(id)}
                  onPin={handlePinToggle}
                  onFavorite={handleFavoriteToggle}
                  onPreview={(id) => handleContractClick(id)}
                  onAnalyze={(id) => toast.info(`AI analyzing contract ${id}...`)}
                  onEdit={(id) => router.push(`/contracts/${id}`)}
                  onDelete={(id) => {
                    setContracts((prev) => prev.filter((c) => c.id !== id));
                    toast.success("Contract deleted");
                  }}
                />
              ))}
            </motion.div>
          ) : (
            <motion.div
              key="timeline"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="bg-white rounded-xl border p-6"
            >
              <p className="text-center text-muted-foreground">
                Timeline view - Integrate with existing ContractTimeline component
              </p>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Contract Preview Panel */}
        <ContractPreviewPanel
          contract={previewContract}
          isOpen={previewOpen}
          onClose={() => setPreviewOpen(false)}
          onNavigate={handlePreviewNavigate}
          onOpenFull={(id) => router.push(`/contracts/${id}`)}
          onEdit={(id) => router.push(`/contracts/${id}?edit=true`)}
          onPin={(id) => {
            handlePinToggle(id);
            if (previewContract) {
              setPreviewContract({ ...previewContract, isPinned: !previewContract.isPinned });
            }
          }}
          onFavorite={(id) => {
            handleFavoriteToggle(id);
            if (previewContract) {
              setPreviewContract({ ...previewContract, isFavorite: !previewContract.isFavorite });
            }
          }}
          onAnalyze={(id) => toast.info(`AI analyzing contract ${id}...`)}
          hasNext={
            previewContract
              ? filteredContracts.findIndex((c) => c.id === previewContract.id) <
                filteredContracts.length - 1
              : false
          }
          hasPrev={
            previewContract
              ? filteredContracts.findIndex((c) => c.id === previewContract.id) > 0
              : false
          }
        />

        {/* Bulk Actions Bar */}
        <EnhancedBulkActionsBar
          selectedCount={selectedIds.length}
          totalCount={filteredContracts.length}
          selectedIds={selectedIds}
          onSelectAll={handleSelectAll}
          onDeselectAll={handleDeselectAll}
          onAction={handleBulkAction}
          availableTags={AVAILABLE_TAGS}
          isLoading={isLoading}
        />
      </div>
    </div>
  );
}
