apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "contigo.fullname" . }}-config
  labels:
    {{- include "contigo.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  NEXT_TELEMETRY_DISABLED: {{ .Values.env.NEXT_TELEMETRY_DISABLED | quote }}
  {{- if .Values.azure.enabled }}
  STORAGE_PROVIDER: "azure"
  AZURE_STORAGE_ACCOUNT: {{ .Values.azure.storageAccount | quote }}
  AZURE_STORAGE_CONTAINER: {{ .Values.azure.storageContainer | quote }}
  {{- end }}
  NEXT_PUBLIC_APP_URL: "https://{{ .Values.ingress.host }}"
  NEXT_PUBLIC_WS_URL: "wss://{{ .Values.ingress.host }}/ws"
