import { defineConfig } from "tsup";

export default defineConfig({
  entry: ["src/server.ts"],
  format: ["cjs"],
  target: "node18",
  sourcemap: true,
  outDir: "dist",
  clean: true,
  bundle: true,
  splitting: false,
  external: [
    "tsconfig-paths/register",
    "utils",
    "clients-db",
    "clients-queue",
    "clients-storage",
    "clients-openai",
    "clients-rag",
    "agents",
    "schemas",
    "openai",
    "pdf-parse",
    "@prisma/client",
    "@opentelemetry/api",
    "@opentelemetry/sdk-node",
    "@opentelemetry/auto-instrumentations-node",
    "@opentelemetry/exporter-trace-otlp-http",
    "@opentelemetry/resources",
    "@opentelemetry/semantic-conventions",
    "pino",
    "pino-pretty",
    "fastify",
    "@fastify/cors",
    "@fastify/compress",
    "@fastify/multipart",
    "@fastify/swagger",
    "@fastify/express",
    "express",
    "bcrypt",
    "jsonwebtoken",
    "bullmq",
    "ioredis",
    "pg",
    "multer",
    "ajv",
    "dotenv",
    "@anthropic-ai/sdk",
    // Langchain packages (used by agents workspace package)
    "langchain",
    "@langchain/core",
    "@langchain/openai",
    "@langchain/community",
    "zod", // Also externalize zod to match langchain's expectations
  ],
  noExternal: [],
});
